/* eslint-disable @next/next/no-page-custom-font */
// eslint-disable-next-line @next/next/no-page-custom-font
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap"
        rel="stylesheet"
      ></link>
      </head>
      <body
    
      >
        <Navbar />
        {children}{" "}
        <footer className="bg-gray-800 text-white py-6">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold">Get Started Today</h2>
            <p className="text-lg mt-4">
              Start downloading your favorite social media videos effortlessly.
            </p>
            <div className="mt-8 flex justify-center space-x-4">
              <a
                href="#"
                className="bg-white text-primary px-6 py-3 rounded-md hover:bg-gray-200 transition"
              >
                Sign Up Now
              </a>
              <a
                href="#"
                className="border border-white px-6 py-3 rounded-md hover:bg-white hover:text-primary transition"
              >
                Learn More
              </a>
            </div>
          </div>
          <div className="container mx-auto text-center">
            <p>&copy; 2024 Lando. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
