import React from 'react'

const Navbar = () => {
  return (
    <nav className="flex p-4 shadow-xl rounded-full  border m-2 w-full px-4">
      <div className="flex w-full justify-between items-center px-5">
        <a
          href="#"
          className="text-slate-700 text-2xl font-extraboldtext-base hover:text-yellow-300 transextraboldduration-300"
        >
          SocialClipSaver
        </a>

        <div className="lg:hidden">
          <button id="hamburger" className="">
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 6h16M4 12h16M4 18h16"
              ></path>
            </svg>
          </button>
        </div>

        <ul className="hidden lg:flex space-x-8 items-center">
          <li>
            <a
              href="/youtube"
              className=" hover:text-yellow-300  transition duration-300"
            >
              YouTube
            </a>
          </li>
          <li>
            <a
              href="instagram"
              className=" hover:text-yellow-300  transition duration-300"
            >
              Instagram
            </a>
          </li>
          <li>
            <a
              href="facebook"
              className=" hover:text-yellow-300  transition duration-300"
            >
              Facebook
            </a>
          </li>
          <li>
            <a
              href="video-generated"
              className=" hover:text-yellow-300  transition duration-300"
            >
              Video Generated by Script
            </a>
          </li>
        </ul>
        <div className="hidden lg:flex space-x-4">
          <a href="login" className="   text-blue-700 transition duration-300">
            Login
          </a>
          <a href="signup" className="   text-blue-700 transition duration-300">
            Sign Up
          </a>
        </div>
      </div>

      <div id="mobile-menu" className="lg:hidden hidden">
        <ul className="flex flex-col space-y-4 bg-blue-700 p-4">
          <li>
            <a
              href="Youtube"
              className=" hover:text-yellow-300  transition duration-300"
            >
              YouTube
            </a>
          </li>
          <li>
            <a
              href="instagram"
              className=" hover:text-yellow-300  transition duration-300"
            >
              Instagram
            </a>
          </li>
          <li>
            <a
              href="facebook"
              className=" hover:text-yellow-300  transition duration-300"
            >
              Facebook
            </a>
          </li>
          <li>
            <a
              href="video-generated"
              className=" hover:text-yellow-300  transition duration-300"
            >
              Video Generated by Script
            </a>
          </li>
          <li>
            <a
              href="login.html"
              className="    hover:bg-green-700 transition duration-300"
            >
              Login
            </a>
          </li>
          <li>
            <a
              href="signup.html"
              className="   hover:bg-yellow-700 transition duration-300"
            >
              Sign Up
            </a>
          </li>
        </ul>
      </div>
    </nav>
  );
}

export default Navbar
