name: Build and Deploy to Red Hat OpenShift

on:
  push:
    branches:
      - master  # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the job runs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx

      - name: Set up Environment Variables
        run: |
          # Create .env file and inject secrets into it
          touch .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
          echo "OPENSHIFT_TOKEN=${{ secrets.OPENSHIFT_TOKEN }}" >> .env
          echo "OPENSHIFT_SERVER=${{ secrets.OPENSHIFT_SERVER }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> .env

      - name: Log in to Docker Hub
        run: |
          # Log in to Docker using the secrets from the .env file
          set -o allexport
          source .env
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: |
          docker build -t youtube-app:latest .  # Build Docker image with the latest tag

      - name: Push Docker image to DockerHub
        run: |
          docker push youtube-app:latest  # Push to your Docker registry (DockerHub, etc.)

  deploy:
    runs-on: ubuntu-latest  # Runs on Ubuntu
    needs: build  # Ensure the build job is completed before deployment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenShift CLI and Log in
        run: |
          set -o allexport
          source .env
          # Log in to OpenShift using the secrets from the .env file
          oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER

      - name: Switch to Existing OpenShift Project
        run: |
          oc project developerhacker-gall-dev  # Use the existing OpenShift project

      - name: Update OpenShift Deployment with New Image and Env Variables
        run: |
          # Update the deployment with the new Docker image
          oc set image deployment/socailmedia socialmedia=youtube-app:latest --record
          oc rollout status deployment/socailmedia

          # Use .env file to set environment variables
          oc set env deployment/socailmedia --from-file=.env

      - name: Expose the OpenShift Service (Route)
        run: |
          # Ensure the service is exposed (creating route if it doesn't exist)
          oc expose svc/socailmedia  # Expose service (create route)

      - name: Get OpenShift Deployment URL
        run: |
          # Show the route URL to access the app
          oc get routes
